### 模型
model_name_or_path: D:\LLaMA-Factory-main\Qwen2.5-0.5B-Instruct

### 训练方式
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: q_proj,v_proj

### 数据集（改这里）
dataset: miao2
template: qwen
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 1
dataloader_num_workers: 0

### 输出（改这里）
output_dir: ./out_nlp
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### 训练参数
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-5
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_steps: 50

### GPU 和精度
bf16: false
fp16: true

### 其他
ddp_timeout: 9000
resume_from_checkpoint: false